### PR TITLE
Update Fet 

### PR DESCRIPTION
**Pull request by FractionEstate**
Fixed

### CODE REVIEW

**Comment by TheTapHouse** [comment]
@FractionEstate supply needs to be adjusted for decimals, currently returning a negative circulating supply

**Comment by FractionEstate** [comment]
Added 1e10 for 10 desimals

**Comment by FractionEstate** [comment]
Tanks to @TheTapHouse for helping providing  a better code 🥇

**Comment by shadowkora** [comment]
Added in #153

**Pull request closed without merging**
