### PR TITLE
Create Catnip.ts

### PR DESCRIPTION
**Pull request by savvycodings**

### CODE REVIEW

**Comment by shadowkora** [comment]
@savvycodings You are missing the fetcher in index.ts

**Comment by savvycodings** [comment]
Ok added fetcher

**Comment by savvycodings** [comment]
ok sweet updated

**Comment by shadowkora** [comment]
@savvycodings Could you perhaps make a new PR? You are modifying 21000 lines of code, just make a new one with the latest repo pulled and modify only the 2 required files.

**Pull request closed without merging**
