### PR TITLE
BURNZ circulating supply

### PR DESCRIPTION
**Pull request by realdecimalist**

### CODE REVIEW

**Comment by realdecimalist** [comment]
What's the issue?

**Review by 0xj4m35 — CHANGES_REQUESTED** [review]
@realdecimalist please run `npm run check-format` to format your code. Also, you changed a lot of content in `index.ts`

**Comment by realdecimalist** [comment]
> @realdecimalist please run `npm run check-format` to format your code. Also, you changed a lot of content in `index.ts`

reverted formatting changes done manually to 'index.ts' and ran 'npx prettier --write .'

**Review by tvtduy59 — APPROVED** [review]
LGTM

**Pull request closed without merging**
