### PR TITLE
Add RJV supply

### PR DESCRIPTION
**Pull request by TheTapHouse**
RJV is part of SingularityNET family and has same endpoint as AGIX and NTX, just with RJV in query parameter.

Matches what is displayed on CMC as well.

### CODE REVIEW

**Comment by TheTapHouse** [comment]
Endpoint is throwing 500 error now.. wait to merge this one.

**Comment by hieupnh** [comment]
@TheTapHouse  I will convert this PR to draft, pls reopen when the endpoint gets the total supply is working

**Comment by TheTapHouse** [comment]
Looks like these endpoints are working now after testing a few times throughout the day. They would throw 500 the second time you tried to load them before.

**Comment by longngn** [comment]
> Looks like these endpoints are working now after testing a few times throughout the day. They would throw 500 the second time you tried to load them before.

can u fix conflict?

**Review by longngn — APPROVED** [review]

**Pull request merged**
