### PR TITLE
Ashib corrected

### PR DESCRIPTION
**Pull request by similiken**
I figured out what the missing return of function is and added to ashib.ts
index.ts has references for ashib

### CODE REVIEW

**Comment by similiken** [comment]
> I figured out what the missing return of function is and added to ashib.ts index.ts has references for ashib

ashib.ts does not invoke axios or blockfrost. we had two token burn events and just need to reflect the new token total.

**Comment by Backsleepaz** [comment]
@longngn Hello.  Any update on this?  We have waited 3 weeks,  need our circulation supply changed.  

Greetings Mike

**Comment by longngn** [comment]
> @longngn Hello. Any update on this? We have waited 3 weeks, need our circulation supply changed.
> 
> Greetings Mike

can you fix conflict and format please

**Comment by similiken** [comment]
index.ts is strange. It's not obvious what of the format i inputted should be changed in any way. Just that the checks simply doesn't like something. running a tiny experiment where i removed the quotation marks from the concatanation of the hex token name and policy id.

**Comment by Backsleepaz** [comment]
> > @longngn Hello. Any update on this? We have waited 3 weeks, need our circulation supply changed.
> > Greetings Mike
> 
> can you fix conflict and format please

@longngn  We should have fixed it now.

**Comment by longngn** [comment]
merge via https://github.com/minswap/market-cap/pull/77

**Pull request closed without merging**
