### PR TITLE
Added MarketRaker circulating supply to MinSwap

### PR DESCRIPTION
**Pull request by cobuscoetsee**
Adding code to show MarketRaker coin circulating supply

### CODE REVIEW

**Comment by longngn** [comment]
please update index.ts

**Comment by cobuscoetsee** [comment]
Updated index.ts accordingly appreciate it. :)

**Comment by TheTapHouse** [comment]
1. run `npm run format` to pass formatting checks
2. the output is { circulating: '10614253999994.799', total: '10614254000000' }, which is ~10 trillion+ circulating but only ~10m total supply.

**Comment by cobuscoetsee** [comment]
Reviewed and done tests, thanks for the guidance.

**Review by shadowkora — APPROVED** [review]

**Pull request merged**
