### PR TITLE
Add DJED and SHEN circulating supply

### PR DESCRIPTION
**Pull request by TheTapHouse**
DJED and SHEN were both minted with a 1 trillion supply that was sent to smart contract to be distributed when someone "mints" DJED/SHEN. I set both circulating and total supply to be tokens that are actually being used (outside of minting smart contract), since the 1 trillion is an arbitrary number, not really reflective of "Total Supply" in the traditional sense.

### CODE REVIEW

**Comment by MuesliSwapTeam** [comment]
Note that technically, the djed and shen contract address is not static. With contract upgrades it can move. The current location is indicated by an NFT (the DjedStableCoinNFT).

**Comment by TheTapHouse** [comment]
@MuesliSwapTeam thanks for the call out, just updated fetchers to get address holding the DjedStableCoinNFT instead of static stake address.

**Comment by MuesliSwapTeam** [comment]
Awesome. This will replace the current code in the MuesliSwap fork of this package.

**Comment by hieupnh** [comment]
@TheTapHouse  thanks for your contribution, btw can you check the result of `circulating` and `total` has the same value: (total - treasury)

**Comment by TheTapHouse** [comment]
@hieupnh The actual onchain supply for both DJED and SHEN are 1 trillion each, but this number is somewhat arbitrary and seems to have been minted so that there should always be enough supply. 

Main reason I set this to be the same as circulating supply is because it wouldn't really make sense for the total market cap of DJED to be $1 trillion. If you think it's better to reflect the actual total onchain supply for the token, we can change them both to be `total: 1e12`, up to you.

**Comment by longngn** [comment]
> @hieupnh The actual onchain supply for both DJED and SHEN are 1 trillion each, but this number is somewhat arbitrary and seems to have been minted so that there should always be enough supply.
> 
> Main reason I set this to be the same as circulating supply is because it wouldn't really make sense for the total market cap of DJED to be $1 trillion. If you think it's better to reflect the actual total onchain supply for the token, we can change them both to be `total: 1e12`, up to you.

LGTM, can you fix the conflicts? then we can merge this PR

**Comment by longngn** [comment]
fixed in https://github.com/minswap/market-cap/pull/61

**Pull request closed without merging**
