### PR TITLE
Mynth (MNT) market-cap addition

### PR DESCRIPTION
**Pull request by SkrowRepap**
Please approve adding the total and circulating supply of Mynth (MNT) token. Thanks.

https://www.mynth.ai/ (Site)
[471d48d89fda4d9fd614109c3a770fc8c45f6d2e](https://cardanoscan.io/token/471d48d89fda4d9fd614109c3a770fc8c45f6d2e) (Policy ID)

## Checks done ✅
- `npm run format`
- `npm run check-format`
- `npm test` with our Blockfrost key

### CODE REVIEW

**Comment by SkrowRepap** [comment]
Seems like rjv token tests is failing. Need advice about this @longngn

**Review by longngn — DISMISSED** [review]

**Comment by longngn** [comment]
> Seems like rjv token tests is failing. Need advice about this @longngn @TheTapHouse

it's fine, we can ignore that token
can you fix conflicts with `main`?

**Comment by SkrowRepap** [comment]
@longngn conflicts have been fixed now @longngn

**Review by longngn — APPROVED** [review]

**Comment by SynthLuvr** [comment]
@shadowkora it's now fixed

**Pull request merged**
